# Generated by Django 5.1.1 on 2025-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_category', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
