# Generated by Django 5.1.1 on 2025-07-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_category', '0006_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
