# Generated by Django 5.2.3 on 2025-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
